rollback deployment added

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -141,17 +141,32 @@ jobs:
               SHOULD_ROLLBACK=false
               echo "Should Rollback : $SHOULD_ROLLBACK"
             fi
+              # Export outputs
+              echo "count_current=$COUNT_CURRENT" >> $GITHUB_OUTPUT
+              echo "version_current=$VERSION_CURRENT" >> $GITHUB_OUTPUT
+              echo "count_previous=$COUNT_PREVIOUS" >> $GITHUB_OUTPUT
+              echo "version_previous=$VERSION_PREVIOUS" >> $GITHUB_OUTPUT
+              echo "should_rollback=$SHOULD_ROLLBACK" >> $GITHUB_OUTPUT          
           fi
-
-          # Export outputs
-          echo "count_current=$COUNT_CURRENT" >> $GITHUB_OUTPUT
-          echo "version_current=$VERSION_CURRENT" >> $GITHUB_OUTPUT
-          echo "count_previous=$COUNT_PREVIOUS" >> $GITHUB_OUTPUT
-          echo "version_previous=$VERSION_PREVIOUS" >> $GITHUB_OUTPUT
-          echo "should_rollback=$SHOULD_ROLLBACK" >> $GITHUB_OUTPUT
           
       - name: Rollback deployment
         if: ${{ steps.query_errors.outputs.should_rollback == 'true' }}
         run: |
           echo "Rolling back to previous version: ${{ steps.query_errors.outputs.version_previous }}"
+          #echo "Rolling back to previous version: ${{ steps.query_errors.outputs.version_previous }}"
           # Add your rollback command here
+
+       # Rollback to previous stable
+      - name: Rollback to previous stable
+        if: ${{ steps.query_errors.outputs.should_rollback == 'true' }}
+        uses: appleboy/ssh-action@v0.1.6
+        with:
+          host: ${{ secrets.VM_IP }}
+          username: ${{ secrets.VM_USER }}
+          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            deployment_version = ${{github.run_number}} - 1
+            docker stop simple-node-app || true
+            docker rm simple-node-app || true
+            docker run -d --name simple-node-app -p 3000:3000 -e VERSION=$deployment_version -e APPINSIGHTS_INSTRUMENTATIONKEY=${{secrets.APPINSIGHTS_INSTRUMENTATIONKEY}} ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/simple-node-app:v$deployment_version
